### ISSUE TITLE
Rewrite to avoid deprecation warnings in Gradle 3.+

### ISSUE THREAD

**Issue by slavashvets** [nebula-plugins/nebula-dependency-recommender-plugin#36]
There are two deprecation warnings in **Gradle 3.3**
```
The ProjectDependency.getProjectConfiguration() method has been deprecated and is scheduled to be removed in Gradle 4.0.
        at org.gradle.api.internal.artifacts.dependencies.DefaultProjectDependency.getProjectConfiguration(DefaultProjectDependency.java:74)
        at org.gradle.api.internal.artifacts.dependencies.DefaultProjectDependency_Decorated.getProjectConfiguration(Unknown Source)
        at netflix.nebula.dependency.recommender.DependencyRecommendationsPlugin.applyRecommendationToDependency(DependencyRecommendationsPlugin.java:37)
        at netflix.nebula.dependency.recommender.DependencyRecommendationsPlugin.access$000(DependencyRecommendationsPlugin.java:18)
        at netflix.nebula.dependency.recommender.DependencyRecommendationsPlugin$1$1.execute(DependencyRecommendationsPlugin.java:55)
        at netflix.nebula.dependency.recommender.DependencyRecommendationsPlugin$1$1.execute(DependencyRecommendationsPlugin.java:51)
...
```

And

```
ModuleDependency.getConfiguration() has been deprecated and is scheduled to be removed in Gradle 4.0. Use ModuleDependency.getTargetConfiguration() instead.
        at org.gradle.api.internal.artifacts.dependencies.AbstractModuleDependency.getConfiguration(AbstractModuleDependency.java:56)
        at org.gradle.api.internal.artifacts.dependencies.DefaultProjectDependency_Decorated.getConfiguration(Unknown Source)
        at org.gradle.api.internal.artifacts.dependencies.DefaultProjectDependency.getProjectConfiguration(DefaultProjectDependency.java:75)
        at org.gradle.api.internal.artifacts.dependencies.DefaultProjectDependency_Decorated.getProjectConfiguration(Unknown Source)
        at netflix.nebula.dependency.recommender.DependencyRecommendationsPlugin.applyRecommendationToDependency(DependencyRecommendationsPlugin.java:37)
        at netflix.nebula.dependency.recommender.DependencyRecommendationsPlugin.access$000(DependencyRecommendationsPlugin.java:18)
        at netflix.nebula.dependency.recommender.DependencyRecommendationsPlugin$1$1.execute(DependencyRecommendationsPlugin.java:55)
        at netflix.nebula.dependency.recommender.DependencyRecommendationsPlugin$1$1.execute(DependencyRecommendationsPlugin.java:51)
...
```

**Comment by slavashvets** [comment]
Thanks for the fix https://github.com/nebula-plugins/nebula-dependency-recommender-plugin/commit/08f18360bad7b5e6c2971e7d7717d98001c18f21
