### ISSUE TITLE
Error when applying the plugin

### ISSUE THREAD

**Issue by gmariotti** [nebula-plugins/nebula-dependency-recommender-plugin#98]
Hi, I'm using Gradle 4.10.3 and when I'm applying the latest version `7.2.1`, I get the below error. I tried to use other Gradle versions, cleaning up my `.gradle` folders but nothing change. Any idea why?

```bash
* What went wrong:
An exception occurred applying plugin request [id: 'nebula.dependency-recommender', version: '7.2.1']
> Failed to apply plugin [id 'nebula.dependency-recommender']
   > Could not create an instance of type netflix.nebula.dependency.recommender.provider.RecommendationProviderContainer_Decorated.
      > com/google/common/base/Supplier

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.plugins.InvalidPluginException: An exception occurred applying plugin request [id: 'nebula.dependency-recommender', version: '7.2.1']
        at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.exceptionOccurred(DefaultPluginRequestApplicator.java:247)
        at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.applyPlugin(DefaultPluginRequestApplicator.java:229)
        at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.applyPlugins(DefaultPluginRequestApplicator.java:148)
        at org.gradle.kotlin.dsl.provider.PluginRequestsHandler.handle(PluginRequestsHandler.kt:49)
        at org.gradle.kotlin.dsl.provider.StandardKotlinScriptEvaluator$InterpreterHost.applyPluginsTo(KotlinScriptEvaluator.kt:183)
        at org.gradle.kotlin.dsl.execution.Interpreter$ProgramHost.applyPluginsTo(Interpreter.kt:356)
        at Program.execute(Unknown Source)
        at org.gradle.kotlin.dsl.execution.Interpreter$ProgramHost.eval(Interpreter.kt:498)
        at org.gradle.kotlin.dsl.execution.Interpreter.eval(Interpreter.kt:164)
        at org.gradle.kotlin.dsl.provider.StandardKotlinScriptEvaluator.evaluate(KotlinScriptEvaluator.kt:112)
        at org.gradle.kotlin.dsl.provider.KotlinScriptPluginFactory$create$1.invoke(KotlinScriptPluginFactory.kt:51)
        at org.gradle.kotlin.dsl.provider.KotlinScriptPluginFactory$create$1.invoke(KotlinScriptPluginFactory.kt:36)
        at org.gradle.kotlin.dsl.provider.KotlinScriptPlugin.apply(KotlinScriptPlugin.kt:34)
        at org.gradle.configuration.BuildOperationScriptPlugin$1$1.run(BuildOperationScriptPlugin.java:69)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:301)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:293)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:175)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.configuration.BuildOperationScriptPlugin$1.execute(BuildOperationScriptPlugin.java:66)
        at org.gradle.configuration.BuildOperationScriptPlugin$1.execute(BuildOperationScriptPlugin.java:63)
        at org.gradle.configuration.internal.DefaultUserCodeApplicationContext.apply(DefaultUserCodeApplicationContext.java:48)
        at org.gradle.configuration.BuildOperationScriptPlugin.apply(BuildOperationScriptPlugin.java:63)
        at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:41)
        at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:26)
        at org.gradle.configuration.project.ConfigureActionsProjectEvaluator.evaluate(ConfigureActionsProjectEvaluator.java:34)
        at org.gradle.configuration.project.LifecycleProjectEvaluator$EvaluateProject.run(LifecycleProjectEvaluator.java:105)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:301)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:293)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:175)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:68)
        at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:687)
        at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:140)
        at org.gradle.execution.TaskPathProjectEvaluator.configure(TaskPathProjectEvaluator.java:35)
        at org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(TaskPathProjectEvaluator.java:60)
        at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:41)
        at org.gradle.initialization.DefaultGradleLauncher$ConfigureBuild.run(DefaultGradleLauncher.java:274)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:301)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:293)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:175)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.initialization.DefaultGradleLauncher.configureBuild(DefaultGradleLauncher.java:182)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:141)
        at org.gradle.initialization.DefaultGradleLauncher.executeTasks(DefaultGradleLauncher.java:124)
        at org.gradle.internal.invocation.GradleBuildController$1.call(GradleBuildController.java:77)
        at org.gradle.internal.invocation.GradleBuildController$1.call(GradleBuildController.java:74)
        at org.gradle.internal.work.DefaultWorkerLeaseService.withLocks(DefaultWorkerLeaseService.java:154)
        at org.gradle.internal.work.StopShieldingWorkerLeaseService.withLocks(StopShieldingWorkerLeaseService.java:38)
        at org.gradle.internal.invocation.GradleBuildController.doBuild(GradleBuildController.java:96)
        at org.gradle.internal.invocation.GradleBuildController.run(GradleBuildController.java:74)
        at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
        at org.gradle.tooling.internal.provider.ValidatingBuildActionRunner.run(ValidatingBuildActionRunner.java:32)
        at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner$3.run(RunAsBuildOperationBuildActionRunner.java:50)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:301)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:293)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:175)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner.run(RunAsBuildOperationBuildActionRunner.java:45)
        at org.gradle.tooling.internal.provider.SubscribableBuildActionRunner.run(SubscribableBuildActionRunner.java:51)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter$1.transform(InProcessBuildActionExecuter.java:47)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter$1.transform(InProcessBuildActionExecuter.java:44)
        at org.gradle.composite.internal.DefaultRootBuildState.run(DefaultRootBuildState.java:79)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:44)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:30)
        at org.gradle.launcher.exec.BuildTreeScopeBuildActionExecuter.execute(BuildTreeScopeBuildActionExecuter.java:39)
        at org.gradle.launcher.exec.BuildTreeScopeBuildActionExecuter.execute(BuildTreeScopeBuildActionExecuter.java:25)
        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:80)
        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:53)
        at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:62)
        at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:34)
        at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:36)
        at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:25)
        at org.gradle.tooling.internal.provider.ParallelismConfigurationBuildActionExecuter.execute(ParallelismConfigurationBuildActionExecuter.java:43)
        at org.gradle.tooling.internal.provider.ParallelismConfigurationBuildActionExecuter.execute(ParallelismConfigurationBuildActionExecuter.java:29)
        at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:59)
        at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:31)
        at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:59)
        at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:44)
        at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:46)
        at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:30)
        at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:67)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
        at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:37)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
        at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
        at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
        at org.gradle.util.Swapper.swap(Swapper.java:38)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
        at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
        at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:62)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
        at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:81)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
        at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
        at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:295)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: org.gradle.api.internal.plugins.PluginApplicationException: Failed to apply plugin [id 'nebula.dependency-recommender']
        at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:160)
        at org.gradle.api.internal.plugins.DefaultPluginManager.apply(DefaultPluginManager.java:130)
        at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator$3.run(DefaultPluginRequestApplicator.java:151)
        at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.applyPlugin(DefaultPluginRequestApplicator.java:225)
        ... 110 more
Caused by: org.gradle.api.reflect.ObjectInstantiationException: Could not create an instance of type netflix.nebula.dependency.recommender.provider.RecommendationProviderContainer_Decorated.
        at org.gradle.internal.reflect.DirectInstantiator.newInstance(DirectInstantiator.java:53)
        at org.gradle.api.internal.ClassGeneratorBackedInstantiator.newInstance(ClassGeneratorBackedInstantiator.java:36)
        at org.gradle.api.internal.plugins.DefaultConvention.instantiate(DefaultConvention.java:264)
        at org.gradle.api.internal.plugins.DefaultConvention.create(DefaultConvention.java:144)
        at netflix.nebula.dependency.recommender.DependencyRecommendationsPlugin.apply(DependencyRecommendationsPlugin.java:56)
        at netflix.nebula.dependency.recommender.DependencyRecommendationsPlugin.apply(DependencyRecommendationsPlugin.java:47)
        at org.gradle.api.internal.plugins.ImperativeOnlyPluginTarget.applyImperative(ImperativeOnlyPluginTarget.java:42)
        at org.gradle.api.internal.plugins.RuleBasedPluginTarget.applyImperative(RuleBasedPluginTarget.java:50)
        at org.gradle.api.internal.plugins.DefaultPluginManager.addPlugin(DefaultPluginManager.java:174)
        at org.gradle.api.internal.plugins.DefaultPluginManager.access$300(DefaultPluginManager.java:50)
        at org.gradle.api.internal.plugins.DefaultPluginManager$AddPluginBuildOperation.run(DefaultPluginManager.java:264)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:301)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:293)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:175)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.plugins.DefaultPluginManager$2.execute(DefaultPluginManager.java:152)
        at org.gradle.api.internal.plugins.DefaultPluginManager$2.execute(DefaultPluginManager.java:149)
        at org.gradle.configuration.internal.DefaultUserCodeApplicationContext.apply(DefaultUserCodeApplicationContext.java:48)
        at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:149)
        ... 113 more
Caused by: java.lang.NoClassDefFoundError: com/google/common/base/Supplier
        at netflix.nebula.dependency.recommender.provider.RecommendationProviderContainer.getMavenBomRecommendationProvider(RecommendationProviderContainer.java:71)
        at netflix.nebula.dependency.recommender.provider.RecommendationProviderContainer.<init>(RecommendationProviderContainer.java:62)
        at netflix.nebula.dependency.recommender.provider.RecommendationProviderContainer_Decorated.<init>(Unknown Source)
        at org.gradle.internal.reflect.DirectInstantiator.newInstance(DirectInstantiator.java:51)
        ... 132 more
Caused by: java.lang.ClassNotFoundException: com.google.common.base.Supplier
        ... 136 more
```

**Comment by ljacomet** [comment]
The most likely explanation is that you have different plugins that pull in `guava` and the selected version does not contain that class.
Can you check the output of `./gradlew buildEnvironment`?

**Comment by gmariotti** [comment]
Here's the output. It seems that no one plugin is pulling `guava` at all

```
classpath
+--- org.jetbrains.kotlin.jvm:org.jetbrains.kotlin.jvm.gradle.plugin:1.3.11
|    \--- org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.11
|         +--- org.jetbrains.kotlin:kotlin-gradle-plugin-api:1.3.11
|         |    +--- org.jetbrains.kotlin:kotlin-stdlib:1.3.11
|         |    |    +--- org.jetbrains.kotlin:kotlin-stdlib-common:1.3.11
|         |    |    \--- org.jetbrains:annotations:13.0
|         |    \--- org.jetbrains.kotlin:kotlin-native-utils:1.3.11
|         |         \--- org.jetbrains.kotlin:kotlin-stdlib:1.3.11 (*)
|         +--- org.jetbrains.kotlin:kotlin-gradle-plugin-model:1.3.11
|         |    \--- org.jetbrains.kotlin:kotlin-stdlib:1.3.11 (*)
|         +--- org.jetbrains.kotlin:kotlin-stdlib:1.3.11 (*)
|         +--- org.jetbrains.kotlin:kotlin-native-utils:1.3.11 (*)
|         +--- org.jetbrains.kotlin:kotlin-compiler-embeddable:1.3.11
|         |    +--- org.jetbrains.kotlin:kotlin-stdlib:1.3.11 (*)
|         |    +--- org.jetbrains.kotlin:kotlin-script-runtime:1.3.11
|         |    \--- org.jetbrains.kotlin:kotlin-reflect:1.3.11
|         |         \--- org.jetbrains.kotlin:kotlin-stdlib:1.3.11 (*)
|         +--- org.jetbrains.kotlin:kotlin-annotation-processing-gradle:1.3.11
|         |    +--- org.jetbrains.kotlin:kotlin-stdlib:1.3.11 (*)
|         |    \--- org.jetbrains.kotlin:kotlin-compiler-embeddable:1.3.11 (*)
|         +--- org.jetbrains.kotlin:kotlin-android-extensions:1.3.11
|         |    \--- org.jetbrains.kotlin:kotlin-compiler-embeddable:1.3.11 (*)
|         +--- org.jetbrains.kotlin:kotlin-compiler-runner:1.3.11
|         |    +--- org.jetbrains.kotlin:kotlin-build-common:1.3.11
|         |    \--- org.jetbrains.kotlin:kotlin-daemon-client:1.3.11
|         +--- org.jetbrains.kotlin:kotlin-scripting-compiler-embeddable:1.3.11
|         \--- org.jetbrains.kotlin:kotlin-reflect:1.3.11 (*)
\--- io.vertx.vertx-plugin:io.vertx.vertx-plugin.gradle.plugin:0.2.0
     \--- gradle.plugin.io.vertx:vertx-gradle-plugin:0.2.0
          +--- org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.3.11
          |    +--- org.jetbrains.kotlin:kotlin-stdlib:1.3.11 (*)
          |    \--- org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.3.11
          |         \--- org.jetbrains.kotlin:kotlin-stdlib:1.3.11 (*)
          +--- com.github.jengelman.gradle.plugins:shadow:4.0.3
          |    +--- org.jdom:jdom2:2.0.6
          |    +--- org.ow2.asm:asm:7.0-beta
          |    +--- org.ow2.asm:asm-commons:7.0-beta
          |    |    +--- org.ow2.asm:asm:7.0-beta
          |    |    +--- org.ow2.asm:asm-tree:7.0-beta
          |    |    |    \--- org.ow2.asm:asm:7.0-beta
          |    |    \--- org.ow2.asm:asm-analysis:7.0-beta
          |    |         \--- org.ow2.asm:asm-tree:7.0-beta (*)
          |    +--- commons-io:commons-io:2.5 -> 2.6
          |    +--- org.apache.ant:ant:1.9.7
          |    |    \--- org.apache.ant:ant-launcher:1.9.7
          |    +--- org.codehaus.plexus:plexus-utils:3.0.24 -> 3.1.0
          |    +--- org.apache.logging.log4j:log4j-core:2.11.0
          |    |    \--- org.apache.logging.log4j:log4j-api:2.11.0
          |    \--- org.vafer:jdependency:2.1.1
          |         \--- commons-io:commons-io:2.6
          \--- com.netflix.nebula:nebula-dependency-recommender:7.2.1
               +--- com.netflix.nebula:nebula-gradle-interop:latest.release -> 1.0.3
               \--- org.apache.maven:maven-model-builder:3.+ -> 3.6.0
                    +--- org.codehaus.plexus:plexus-utils:3.1.0
                    +--- org.codehaus.plexus:plexus-interpolation:1.25
                    +--- org.codehaus.plexus:plexus-component-annotations:1.7.1
                    +--- org.apache.maven:maven-model:3.6.0
                    |    \--- org.codehaus.plexus:plexus-utils:3.1.0
                    +--- org.apache.maven:maven-artifact:3.6.0
                    |    +--- org.codehaus.plexus:plexus-utils:3.1.0
                    |    \--- org.apache.commons:commons-lang3:3.8.1
                    \--- org.apache.maven:maven-builder-support:3.6.0
```

**Comment by rpalcolea** [comment]
Hi @gmariotti ,

Thanks for reporting this issue. Just released `v7.2.2` with a fix for it and verified against `4.10.3` -> https://github.com/rpalcolea/nebula-dependency-recommender-guava-issue

**Comment by gmariotti** [comment]
Tried with `5.1` and it is working too. However, how is it possible that nobody noticed this issue before? I tried all `7.x` versions and I constantly received this error

**Comment by rpalcolea** [comment]
This should be resolved on newest versions.

The problem is usually caused by higher or lower versions of Guava in the classpath. Nebula plugin won't have control on this

**Comment by velbon** [comment]
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/gerald/jd-gui/build.gradle' line: 15

* What went wrong:
A problem occurred evaluating root project 'jd-gui'.
> Failed to apply plugin class 'com.netflix.gradle.plugins.packaging.SystemPackagingBasePlugin'.
   > Could not create an instance of type com.netflix.gradle.plugins.packaging.ProjectPackagingExtension.
      > Could not find matching constructor for: org.gradle.api.internal.file.copy.DefaultCopySpec(org.gradle.api.internal.file.BaseDirFileResolver, org.gradle.internal.instantiation.generator.DependencyInjectingInstantiator)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/8.0.1/userguide/command_line_interface.html#sec:command_line_warnings
